version: '3.8'

services:
  ai-service:
    build: 
      context: .
      target: build
    container_name: ai-service
    ports:
      - "8090:8080"
    volumes:
      - .:/build
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run -Dspring-boot.run.profiles=docker
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
