version: '3.8'

services:
  ai-service:
    image: truongikpk/bookstore-ai-service:v1.0.0
    container_name: ai-service
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
